/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.proizvodjac;

import domen.Drzava;
import domen.OpstiDomenskiObjekat;
import domen.Proizvodjac;
import helper.Helper;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import komunikacija.Komunikacija;
import konstante.Konstante;
import transfer.KlijentTransferObjekat;
import transfer.ServerTransferObjekat;

/**
 *
 * @author Jovan
 */
public class FrmProizvodjacUnos extends javax.swing.JPanel {

    FrmProizvodjaci parent;

    /**
     * Creates new form FrmProizvodjacUnos
     */
    public FrmProizvodjacUnos(FrmProizvodjaci parent) {
        initComponents();
        this.parent = parent;
        srediFormu();
        Proizvodjac pr = (Proizvodjac) Helper.getInstance().get("pr");
        if (pr != null) {
            prikazProizvodjaca(pr);
            jButtonSacuvajProizvodjaca.setText("Sačuvaj izmene");
            jTextFieldIDProizvodjaca.setEnabled(false);
            Helper.getInstance().remove("pr");
        } else {
            srediFormu();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNazivProizvodjaca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIDProizvodjaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxDrzava = new javax.swing.JComboBox();
        jButtonSacuvajProizvodjaca = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();

        jLabel1.setText("Naziv proizvođača:");

        jLabel2.setText("ID proizvođača:");

        jLabel3.setText("Država sedište proizvođača:");

        jComboBoxDrzava.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonSacuvajProizvodjaca.setText("Sačuvaj proizvođača");
        jButtonSacuvajProizvodjaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajProizvodjacaActionPerformed(evt);
            }
        });

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxDrzava, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNazivProizvodjaca)
                            .addComponent(jTextFieldIDProizvodjaca, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSacuvajProizvodjaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(jButtonOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIDProizvodjaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNazivProizvodjaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSacuvajProizvodjaca)
                    .addComponent(jButtonOdustani))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSacuvajProizvodjacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajProizvodjacaActionPerformed
        try {
            int id = 0;
            String naziv = "";

            boolean treba = false;
            if (!jTextFieldIDProizvodjaca.equals("")) {
                id = Integer.parseInt(jTextFieldIDProizvodjaca.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Morate uneti neiskorišćeni ID");
                return;
            }
            if (!jTextFieldNazivProizvodjaca.equals("")) {
                naziv = jTextFieldNazivProizvodjaca.getText().trim();
            } else {
                JOptionPane.showMessageDialog(this, "Morate uneti naziv proizvođača");
                return;
            }

            Drzava drz = (Drzava) jComboBoxDrzava.getSelectedItem();
            Proizvodjac p = new Proizvodjac(id, naziv, drz);

            KlijentTransferObjekat kto = new KlijentTransferObjekat();

            if (jButtonSacuvajProizvodjaca.getText().equals("Sačuvaj proizvođača")) {
                kto.setOperacija(Konstante.DODAJ_PROIZVODJACA);
            } else {
                kto.setOperacija(Konstante.IZMENI_PROIZVODJACA);
                treba = true;
            }
            kto.setParametar(p);
            Komunikacija.getInstance().posaljiZahtev(kto);
            ServerTransferObjekat sto = Komunikacija.getInstance().procitajOdgovor();
            if (sto.getRezultat() == Konstante.REZULTAT_NOK) {
                throw new Exception(sto.getIzuzetak());
            }
            JOptionPane.showMessageDialog(this, "Proizvođač je uspešno sačuvan!");
            if (treba) {
                parent.srediFormu();
            }
            SwingUtilities.getWindowAncestor(this).setVisible(false);

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Proizvođač nije sačuvan!");
        }
    }//GEN-LAST:event_jButtonSacuvajProizvodjacaActionPerformed

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        SwingUtilities.getWindowAncestor(this).setVisible(false);
    }//GEN-LAST:event_jButtonOdustaniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonSacuvajProizvodjaca;
    private javax.swing.JComboBox jComboBoxDrzava;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldIDProizvodjaca;
    private javax.swing.JTextField jTextFieldNazivProizvodjaca;
    // End of variables declaration//GEN-END:variables
    public void srediFormu() {
        try {
            KlijentTransferObjekat kto = new KlijentTransferObjekat();
            kto.setOperacija(Konstante.VRATI_DRZAVE);
            Komunikacija.getInstance().posaljiZahtev(kto);
            ServerTransferObjekat sto = Komunikacija.getInstance().procitajOdgovor();
            List<OpstiDomenskiObjekat> ld = (List<OpstiDomenskiObjekat>) sto.getOdgovor();
            jComboBoxDrzava.removeAllItems();
            for (OpstiDomenskiObjekat d : ld) {
                Drzava drz = (Drzava) d;//ovde ako nece ucitavanje
                jComboBoxDrzava.addItem(drz);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void prikazProizvodjaca(Proizvodjac p) {
        jTextFieldIDProizvodjaca.setText(p.getProizvodjacID() + "");
        jTextFieldNazivProizvodjaca.setText(p.getNazivProizvodjaca());
        jComboBoxDrzava.setSelectedItem(p.getDrzava());

    }

}
