/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.glavna.logovanje;

import domen.Prodavac;
import forme.model.FrmModelUnos;
import forme.model.FrmModeli;
import forme.proizvodjac.FrmProizvodjacUnos;
import forme.proizvodjac.FrmProizvodjaci;
import forme.racun.FrmRacunUnos;
import forme.racun.FrmRacuni;
import helper.Helper;
import java.awt.BorderLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Jovan
 */
public class FrmGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FrmGlavna
     */
    public FrmGlavna() {
        initComponents();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        jLabelDatum.setText(dateFormat.format(date));
        Prodavac p = (Prodavac) Helper.getInstance().get("p");
        jTextFieldKao.setText(p.getImePrezime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldKao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelDatum = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuModeli = new javax.swing.JMenu();
        jMenuItemUnosModela = new javax.swing.JMenuItem();
        jMenuItemPrikazModela = new javax.swing.JMenuItem();
        jMenuProizvodjaci = new javax.swing.JMenu();
        jMenuItemUnosProizvodjaca = new javax.swing.JMenuItem();
        jMenuItemPrikazProizvođača = new javax.swing.JMenuItem();
        jMenuRacuni = new javax.swing.JMenu();
        jMenuItemPrikazRacuna = new javax.swing.JMenuItem();
        jMenuItemNoviRacun = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem5.setText("jMenuItem5");

        jMenu1.setText("File");
        jMenuBar3.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar3.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Prijavljeni ste kao:");

        jTextFieldKao.setEditable(false);

        jLabel2.setText("Danas je: ");

        jMenuModeli.setText("Modeli gitara");

        jMenuItemUnosModela.setText("Unos modela gitare");
        jMenuItemUnosModela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosModelaActionPerformed(evt);
            }
        });
        jMenuModeli.add(jMenuItemUnosModela);

        jMenuItemPrikazModela.setText("Prikaz modela gitare");
        jMenuItemPrikazModela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazModelaActionPerformed(evt);
            }
        });
        jMenuModeli.add(jMenuItemPrikazModela);

        jMenuBar1.add(jMenuModeli);

        jMenuProizvodjaci.setText("Proizvođači");

        jMenuItemUnosProizvodjaca.setText("Unos proizvođača");
        jMenuItemUnosProizvodjaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosProizvodjacaActionPerformed(evt);
            }
        });
        jMenuProizvodjaci.add(jMenuItemUnosProizvodjaca);

        jMenuItemPrikazProizvođača.setText("Prikaz proizvođača");
        jMenuItemPrikazProizvođača.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazProizvođačaActionPerformed(evt);
            }
        });
        jMenuProizvodjaci.add(jMenuItemPrikazProizvođača);

        jMenuBar1.add(jMenuProizvodjaci);

        jMenuRacuni.setText("Računi");

        jMenuItemPrikazRacuna.setText("Prikaz računa");
        jMenuItemPrikazRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazRacunaActionPerformed(evt);
            }
        });
        jMenuRacuni.add(jMenuItemPrikazRacuna);

        jMenuItemNoviRacun.setText("Novi račun");
        jMenuItemNoviRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNoviRacunActionPerformed(evt);
            }
        });
        jMenuRacuni.add(jMenuItemNoviRacun);

        jMenuBar1.add(jMenuRacuni);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldKao, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldKao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUnosProizvodjacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosProizvodjacaActionPerformed
        FrmProizvodjacUnos f = new FrmProizvodjacUnos(null);
        JDialog d = new JDialog(this, "Unos proizvođača", true);
        d.setLayout(new BorderLayout());
        d.add(f, BorderLayout.CENTER);
        d.pack();
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItemUnosProizvodjacaActionPerformed

    private void jMenuItemPrikazProizvođačaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazProizvođačaActionPerformed
        try {

            FrmProizvodjaci f = new FrmProizvodjaci();
            JDialog d = new JDialog(this, "Prikaz proizvođača", true);
            d.setLayout(new BorderLayout());
            d.add(f, BorderLayout.CENTER);
            d.pack();
            JOptionPane.showMessageDialog(d, "Proizvođači su učitani");
            d.setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da pronađe proizvođače");
            Logger.getLogger(FrmGlavna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemPrikazProizvođačaActionPerformed

    private void jMenuItemPrikazRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazRacunaActionPerformed
        FrmRacuni f = new FrmRacuni();
        JDialog d = new JDialog(this, "Prikaz računa", true);
        d.setLayout(new BorderLayout());
        d.add(f, BorderLayout.CENTER);
        d.pack();
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItemPrikazRacunaActionPerformed

    private void jMenuItemNoviRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNoviRacunActionPerformed
        FrmRacunUnos f = new FrmRacunUnos();
        JDialog d = new JDialog(this, "Unos računa", true);
        d.setLayout(new BorderLayout());
        d.add(f, BorderLayout.CENTER);
        d.pack();
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItemNoviRacunActionPerformed

    private void jMenuItemUnosModelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosModelaActionPerformed
        FrmModelUnos f = new FrmModelUnos();
        JDialog d = new JDialog(this, "Unos modela", true);
        d.setLayout(new BorderLayout());
        d.add(f, BorderLayout.CENTER);
        d.pack();
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItemUnosModelaActionPerformed

    private void jMenuItemPrikazModelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazModelaActionPerformed
        try {
            FrmModeli f = new FrmModeli();
            JDialog d = new JDialog(this, "Prikaz modela gitare", true);
            d.setLayout(new BorderLayout());
            d.add(f, BorderLayout.CENTER);
            d.pack();
            d.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FrmGlavna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemPrikazModelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGlavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDatum;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemNoviRacun;
    private javax.swing.JMenuItem jMenuItemPrikazModela;
    private javax.swing.JMenuItem jMenuItemPrikazProizvođača;
    private javax.swing.JMenuItem jMenuItemPrikazRacuna;
    private javax.swing.JMenuItem jMenuItemUnosModela;
    private javax.swing.JMenuItem jMenuItemUnosProizvodjaca;
    private javax.swing.JMenu jMenuModeli;
    private javax.swing.JMenu jMenuProizvodjaci;
    private javax.swing.JMenu jMenuRacuni;
    private javax.swing.JTextField jTextFieldKao;
    // End of variables declaration//GEN-END:variables
}
