/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.model;

import domen.ModelGitare;
import domen.OpstiDomenskiObjekat;
import domen.Proizvodjac;
import helper.Helper;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import komunikacija.Komunikacija;
import konstante.Konstante;
import transfer.KlijentTransferObjekat;
import transfer.ServerTransferObjekat;

/**
 *
 * @author Jovan
 */
public class FrmModelUnos extends javax.swing.JPanel {

    FrmModeli parent;

    /**
     * Creates new form FrmModelUnos
     */
    public FrmModelUnos() {
        initComponents();
        this.parent = parent;
        srediFormu();
        ModelGitare mg = (ModelGitare) Helper.getInstance().get("mg");
        if (mg != null) {
            prikazModela(mg);
            jButtonSacuvaj.setText("Izmeni");
            jTextFieldIDModela.setEnabled(false);
            Helper.getInstance().remove("mg");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIDModela = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonNovo = new javax.swing.JRadioButton();
        jRadioButtonPolovno = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldOznaka = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCena = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldGarancija = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldMagneti = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPragovi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTelo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldBoja = new javax.swing.JTextField();
        jComboBoxProizvodjac = new javax.swing.JComboBox();
        jButtonSacuvaj = new javax.swing.JButton();

        jLabel1.setText("ID modela gitare:");

        jLabel2.setText("Status:");

        buttonGroup1.add(jRadioButtonNovo);
        jRadioButtonNovo.setText("Novo");

        buttonGroup1.add(jRadioButtonPolovno);
        jRadioButtonPolovno.setText("Polovno");

        jLabel3.setText("Oznaka:");

        jLabel4.setText("Cena:");

        jLabel5.setText("Garancija:");

        jLabel6.setText("Magneti:");

        jLabel7.setText("Pragovi:");

        jLabel8.setText("Telo:");

        jLabel9.setText("Boja:");

        jLabel10.setText("Proizvođač:");

        jComboBoxProizvodjac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonSacuvaj.setText("Sačuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2)
                            .add(jLabel3)
                            .add(jLabel4)
                            .add(jLabel5)
                            .add(jLabel6)
                            .add(jLabel7)
                            .add(jLabel8)
                            .add(jLabel9)
                            .add(jLabel10))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(jTextFieldOznaka)
                                .add(jTextFieldCena)
                                .add(jTextFieldGarancija, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jTextFieldMagneti)
                                .add(jTextFieldPragovi)
                                .add(jTextFieldTelo)
                                .add(jTextFieldBoja)
                                .add(jComboBoxProizvodjac, 0, 143, Short.MAX_VALUE))
                            .add(jTextFieldIDModela, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(jRadioButtonNovo)
                                .add(18, 18, 18)
                                .add(jRadioButtonPolovno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jButtonSacuvaj))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTextFieldIDModela, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jRadioButtonNovo)
                    .add(jRadioButtonPolovno))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jTextFieldOznaka, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jTextFieldCena, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jTextFieldGarancija, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(jTextFieldMagneti, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(jTextFieldPragovi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(jTextFieldTelo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(jTextFieldBoja, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(jComboBoxProizvodjac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jButtonSacuvaj)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        try {
            int id = 0;
            String oznaka = "";
            double cena = 0;
            int garancija = 0;
            String magneti = "";
            String pragovi = "";
            String telo = "";
            String boja = "";
            if (!jTextFieldIDModela.getText().equals("")) {
                id = Integer.parseInt(jTextFieldIDModela.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Morate uneti neiskorišćen ID");
                return;
            }

            if (!jTextFieldOznaka.getText().equals("")) {
                oznaka = jTextFieldOznaka.getText().trim();
            } else {
                JOptionPane.showMessageDialog(this, "Morate uneti oznaku modela");
                return;
            }

            String status = "nepoznato";
            if (jRadioButtonNovo.isSelected()) {
                status = "Novo";
            } else if (jRadioButtonPolovno.isSelected()) {
                status = "Polovno";
            }

            if (!jTextFieldCena.getText().equals("")) {
                cena = Double.parseDouble(jTextFieldCena.getText().trim());
            } else {
                JOptionPane.showMessageDialog(this, "Morate uneti cenu modela");
                return;
            }
            if (!jTextFieldGarancija.getText().equals("")) {
                garancija = Integer.parseInt(jTextFieldGarancija.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Morate uneti trajanje garancije za model");
                return;
            }

            if (!jTextFieldMagneti.getText().equals("")) {
                magneti = jTextFieldMagneti.getText().trim();
            } else {
                JOptionPane.showMessageDialog(this, "Morate uneti opis magneta");
                return;
            }

            if (!jTextFieldPragovi.getText().equals("")) {
                pragovi = jTextFieldPragovi.getText().trim();
            } else {
                JOptionPane.showMessageDialog(this, "Morate uneti broj pragova");
                return;
            }
            if (!jTextFieldTelo.getText().equals("")) {
                telo = jTextFieldTelo.getText().trim();
            } else {
                JOptionPane.showMessageDialog(this, "Morate uneti opis tela modela");
                return;
            }
            if (!jTextFieldBoja.getText().equals("")) {
                boja = jTextFieldBoja.getText().trim();
            } else {
                JOptionPane.showMessageDialog(this, "Morate uneti boju modela");
                return;
            }

            Proizvodjac p = (Proizvodjac) jComboBoxProizvodjac.getSelectedItem();

            ModelGitare mg = new ModelGitare(id, cena, status, oznaka, garancija, magneti, pragovi, telo, boja, p);

            KlijentTransferObjekat kto = new KlijentTransferObjekat();

            if (jButtonSacuvaj.getText().equals("Sačuvaj")) {
                kto.setOperacija(Konstante.DODAJ_MODEL);
            } else {
                kto.setOperacija(Konstante.IZMENI_MODEL);
            }
            kto.setParametar(mg);
            Komunikacija.getInstance().posaljiZahtev(kto);
            ServerTransferObjekat sto = Komunikacija.getInstance().procitajOdgovor();
            if (sto.getRezultat() == Konstante.REZULTAT_NOK) {
                throw new Exception(sto.getIzuzetak());
            }
            JOptionPane.showMessageDialog(this, "Model je uspešno sačuvan!");
            SwingUtilities.getWindowAncestor(this).setVisible(false);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Model nije sačuvan!");
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButtonSacuvajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JComboBox jComboBoxProizvodjac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonNovo;
    private javax.swing.JRadioButton jRadioButtonPolovno;
    private javax.swing.JTextField jTextFieldBoja;
    private javax.swing.JTextField jTextFieldCena;
    private javax.swing.JTextField jTextFieldGarancija;
    private javax.swing.JTextField jTextFieldIDModela;
    private javax.swing.JTextField jTextFieldMagneti;
    private javax.swing.JTextField jTextFieldOznaka;
    private javax.swing.JTextField jTextFieldPragovi;
    private javax.swing.JTextField jTextFieldTelo;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        try {
            KlijentTransferObjekat kto = new KlijentTransferObjekat();
            kto.setOperacija(Konstante.VRATI_PROIZVODJACE);
            Komunikacija.getInstance().posaljiZahtev(kto);
            ServerTransferObjekat sto = Komunikacija.getInstance().procitajOdgovor();
            List<OpstiDomenskiObjekat> lpr = (List<OpstiDomenskiObjekat>) sto.getOdgovor();
            jComboBoxProizvodjac.removeAllItems();
            for (OpstiDomenskiObjekat pr : lpr) {
                jComboBoxProizvodjac.addItem((Proizvodjac) pr);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void prikazModela(ModelGitare mg) {
        jTextFieldIDModela.setText(mg.getModelGitareID() + "");
        jTextFieldCena.setText(mg.getCenaModela() + "");
        jTextFieldPragovi.setText(mg.getPragovi());
        jTextFieldGarancija.setText(mg.getGarancija() + "");
        jTextFieldTelo.setText(mg.getTelo());
        jTextFieldBoja.setText(mg.getBoja());
        jTextFieldMagneti.setText(mg.getMagneti());
        jTextFieldOznaka.setText(mg.getOznakaModela());
        jComboBoxProizvodjac.setSelectedItem(mg.getProizvodjac());
        if (mg.getStatusModela().equals("Stariji")) {
            jRadioButtonPolovno.setSelected(true);
        } else {
            jRadioButtonNovo.setSelected(true);
        }
    }

}
